### PR TITLE
test branch

### PR DESCRIPTION
**Pull request by alemapnil**
嘗試操作Guide - Part 0的8. Pull Request.
預期將develop的test.txt合併至我的main，請老師審核一下我這樣的git流程合乎規則否?
如果正確，以後我就照這流程操作

### CODE REVIEW

**Comment by cwpeng** [comment]
Please add rule to `main` branch: require at least 1 review approval before merging. You will see the changes in this page if you finished setup it.

**Comment by alemapnil** [comment]
@cwpeng 
Thank you for your reply.
Actually I don't understand what kind of changes you talked about.
But I can see your reply as below and I've added protection rule to my branch "develop" according Guide_-_Part_0.pdf.
So do I succeed in git process (8. Pull Request) you command us?

**Comment by cwpeng** [comment]
Where you get this?

> I've added protection rule to my branch "develop" according Guide_-_Part_0.pdf.

In my guide, I say:

> 3. Review Rule
> 請至 GitHub 網站的專案設定中 Branches 管理工具，為你的 main 分支新增管理規則：Require a pull request before merging 以及 Require at least 1 approval 才能合併。( 建立規則時，輸入要套用的分支名稱，並且將相關的規則選項打勾 )

In my comment, I say:

1. add rule to `main` branch.
2. you will see the changes in this page if you finished setup it.

Try to change it.

**Comment by cwpeng** [comment]
And you should leave your name in pull request message, or I cannot know who you are.

**Comment by alemapnil** [comment]
I'm 林婉茹.
I've added rule to "main" as below, please check.

.

**Review by cwpeng — APPROVED** [review]
OK. Try to change port to 3000 in another pull request.

**Comment by alemapnil** [comment]
Sorry, I don't get it. 
What does it mean "Try to change port to 3000 in another pull request."?

**Comment by cwpeng** [comment]
按照指引，我們要把程式碼中的 port 換成 3000，你還沒在這個 Pull Request 中執行。

Pull Request 完成 Review 之後你就可以做 Merge。然後繼續執行下一件該做的事情，做完後發另一個 Pull Request 來要求我做 Review。

**Pull request merged**
