### PR TITLE
完成 Part1-1 & Part1-2

### PR DESCRIPTION
**Pull request by alemapnil**
放程式碼在Github，再進行Part 1 - 3

### CODE REVIEW

**Comment by cwpeng** [comment]
You can create pull request, push commits to GitHub. But, if you haven't finished task, don't ask for review.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Not Finished.

**Comment by alemapnil** [comment]
completed.

http://107.23.214.243:3000/api/attractions/?page=1
http://107.23.214.243:3000/api/attractions/?page=1&keyword=北
http://107.23.214.243:3000/api/attraction/8

**Comment by cwpeng** [comment]
Response format of http://107.23.214.243:3000/api/attractions/?page=4 is not correct. Check API spec carefully, fix it and request me review from right side of this page again.

**Comment by alemapnil** [comment]
I've modified according to API spec.
Please check above url again.

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Pull request merged**
